# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33ae1ed8249a85860017aa52d740e4701e962f8254198b360536a4aae6410077ea4383c8f107a49096b40ec00e49f11e0b0b8bafe5e6fe1892afb0d13a67f2d1

test:
  secret_key_base: fc5bd1f86b4ea961d7bd89d8491e2921f200358b76b5a165d44ad4c17009b9fcff7c36184cde6ef0c74585238dd445c547d871cdbfbefe9bd1a0f6eb70c8f008

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
